// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {presets} from '../models';
import {dutix} from '../models';
import {autoupdate} from '../models';
import {binary} from '../models';
import {snapshots} from '../models';
import {logs} from '../models';

export function ApplyAppUpdateAndRestart(arg1:string):Promise<void>;

export function ApplyPreset(arg1:presets.Preset,arg2:boolean):Promise<Array<dutix.DryRunResult>>;

export function CheckForAppUpdate():Promise<autoupdate.UpdateCheckResult>;

export function CheckForUpdates():Promise<binary.GitHubRelease>;

export function ClearLogs():Promise<void>;

export function CreateSnapshot(arg1:string):Promise<snapshots.Snapshot>;

export function DeletePreset(arg1:string):Promise<void>;

export function DeleteSnapshot(arg1:string):Promise<void>;

export function DetectConflicts():Promise<Array<dutix.ConflictItem>>;

export function DownloadAndInstallBinary():Promise<string>;

export function DownloadAppUpdate():Promise<string>;

export function ExportPresetJSON(arg1:presets.Preset):Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetBinaryStatus():Promise<dutix.BinaryStatus>;

export function GetLogs():Promise<Array<logs.ExecutionLog>>;

export function GetSnapshot(arg1:string):Promise<snapshots.Snapshot>;

export function ImportPresetJSON(arg1:string):Promise<presets.Preset>;

export function ListApps(arg1:string):Promise<Array<dutix.AppInfo>>;

export function ListPresets():Promise<Array<presets.Preset>>;

export function ListSnapshots():Promise<Array<snapshots.Snapshot>>;

export function ListTargets(arg1:string):Promise<Array<dutix.TargetItem>>;

export function MigrateApps(arg1:string,arg2:string,arg3:boolean):Promise<dutix.DryRunResult>;

export function RestoreSnapshot(arg1:string):Promise<snapshots.RollbackReport>;

export function SavePreset(arg1:presets.Preset):Promise<void>;

export function SetCustomBinaryPath(arg1:string):Promise<void>;

export function SetHandler(arg1:string,arg2:Array<string>,arg3:Array<string>,arg4:Array<string>,arg5:boolean):Promise<dutix.DryRunResult>;

export function ShowApp(arg1:string):Promise<dutix.AppDetail>;

export function ShowTarget(arg1:string):Promise<dutix.TargetDetail>;
