// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyPreset(arg1, arg2) {
  return window['go']['main']['App']['ApplyPreset'](arg1, arg2);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function CreateSnapshot(arg1) {
  return window['go']['main']['App']['CreateSnapshot'](arg1);
}

export function DeletePreset(arg1) {
  return window['go']['main']['App']['DeletePreset'](arg1);
}

export function DeleteSnapshot(arg1) {
  return window['go']['main']['App']['DeleteSnapshot'](arg1);
}

export function DetectConflicts() {
  return window['go']['main']['App']['DetectConflicts']();
}

export function DownloadAndInstallBinary() {
  return window['go']['main']['App']['DownloadAndInstallBinary']();
}

export function ExportPresetJSON(arg1) {
  return window['go']['main']['App']['ExportPresetJSON'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetBinaryStatus() {
  return window['go']['main']['App']['GetBinaryStatus']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetSnapshot(arg1) {
  return window['go']['main']['App']['GetSnapshot'](arg1);
}

export function ImportPresetJSON(arg1) {
  return window['go']['main']['App']['ImportPresetJSON'](arg1);
}

export function ListApps(arg1) {
  return window['go']['main']['App']['ListApps'](arg1);
}

export function ListPresets() {
  return window['go']['main']['App']['ListPresets']();
}

export function ListSnapshots() {
  return window['go']['main']['App']['ListSnapshots']();
}

export function ListTargets(arg1) {
  return window['go']['main']['App']['ListTargets'](arg1);
}

export function MigrateApps(arg1, arg2, arg3) {
  return window['go']['main']['App']['MigrateApps'](arg1, arg2, arg3);
}

export function RestoreSnapshot(arg1) {
  return window['go']['main']['App']['RestoreSnapshot'](arg1);
}

export function SavePreset(arg1) {
  return window['go']['main']['App']['SavePreset'](arg1);
}

export function SetCustomBinaryPath(arg1) {
  return window['go']['main']['App']['SetCustomBinaryPath'](arg1);
}

export function SetHandler(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetHandler'](arg1, arg2, arg3, arg4, arg5);
}

export function ShowApp(arg1) {
  return window['go']['main']['App']['ShowApp'](arg1);
}

export function ShowTarget(arg1) {
  return window['go']['main']['App']['ShowTarget'](arg1);
}
